# Site settings
title: derrickorama
tagline: Splish-splashing in the mind of a web dev.
baseurl: ""
url: "https://derrickorama.com"

twitter_username: derrickorama
github_username:  derrickorama
gplus_username: DerrickGall

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-redirect-from
  - jekyll-press
